using TableTop.Core.Abstractions.Cards;
using TableTop.Core.Abstractions.Players;
using TableTop.Core.Abstractions.Scoring;
using TableTop.Core.Domain.Cards;
using TableTop.Core.Domain.Scoring;
using TableTop.Games.Base;

namespace TableTop.Games.School;

/// <summary>
/// Math 24 — four numbers, make 24.
///
/// How to play:
///   1. The reader draws a card and reads the four numbers aloud.
///   2. Everyone works at once. Use <b>all four</b> numbers <b>exactly once</b>,
///      combining them with + − × ÷ and brackets in any order.
///   3. First player to call a correct expression takes the card. The table
///      checks the arithmetic — that check is half the learning.
///   4. Flip for a worked solution. Most puzzles have several; the printed one
///      is only the shortest, and a different valid route still scores.
///
/// <para>
/// <b>Every puzzle on every card is solvable.</b> That is not a claim made by
/// eye — the whole deck was generated by an exhaustive solver over all
/// parenthesisations of + − × ÷, run in exact rational arithmetic so routes
/// through fractional intermediates are found rather than lost to floating
/// point. Two quads that looked obviously fine while hand-picking —
/// <c>4 4 6 6</c> and <c>1 1 8 12</c> — turned out to have no solution at all
/// and were rejected by that run. An unsolvable card in a maths game is not a
/// content nit: it is a child told to keep trying at something impossible. So
/// the deck is machine-checked rather than proofread.
/// </para>
///
/// <para>
/// Difficulty is the solver's count, not a guess. <b>Warm-Up</b> quads have
/// many routes to 24; <b>Steady</b> fewer; <b>Tricky</b> one or two. Every
/// <b>Legendary</b> card is one where <i>every</i> route passes through a
/// non-integer intermediate — you cannot get there while keeping whole
/// numbers at each step. That is why <c>1 3 4 6</c> defeats most adults: the
/// only way in is 6 ÷ (1 − 3∕4), and nothing about the four numbers suggests
/// thirds and quarters.
/// </para>
/// </summary>
public sealed class Math24Mode : BaseGameModeDefinition
{
    /// <inheritdoc />
    public override string Name => "Math 24";

    /// <inheritdoc />
    public override string Description =>
        "Four numbers, all four used once, any of + − × ÷ — make exactly 24. Worked solution on the flip.";

    /// <summary>Label for the button that records a solved puzzle.</summary>
    public override string CompleteLabel => "Got 24!";

    /// <summary>Label for the button that concedes a puzzle.</summary>
    public override string SkipLabel => "Pass";

    /// <summary>Category → hex colour map used by UIs to tint card chrome.</summary>
    public override IReadOnlyDictionary<string, string> CategoryColours =>
        new Dictionary<string, string>
        {
            [Math24CardBank.WarmUpCategory] = "#66BB6A",
            [Math24CardBank.SteadyCategory] = "#42A5F5",
            [Math24CardBank.TrickyCategory] = "#FFA726",
            [Math24CardBank.LegendaryCategory] = "#EF5350",
        };

    /// <summary>Harder puzzles score more — a Legendary card is worth the fight.</summary>
    protected override IScoringStrategy BuildScoring() =>
        new DifficultyBasedScoringStrategy();

    /// <summary>Returns the built-in Math 24 card bank.</summary>
    protected override IReadOnlyList<ICard> BuildCards(IReadOnlyList<IPlayer> players) =>
        Math24CardBank.All;

    /// <summary>Returns the card collection for this game mode.</summary>
    public static IReadOnlyList<ICard> GetCards() => Math24CardBank.All;
}

/// <summary>
/// Built-in card bank for Math 24. Every entry was emitted by the solver
/// described on <see cref="Math24Mode"/>, and the trailing comment on each
/// card records how many distinct solutions that quad has — which is what
/// its difficulty tier is derived from, rather than an author's impression.
/// </summary>
public static class Math24CardBank
{
    internal const string WarmUpCategory = "Warm-Up";
    internal const string SteadyCategory = "Steady";
    internal const string TrickyCategory = "Tricky";
    internal const string LegendaryCategory = "Legendary";

    /// <summary>All Math 24 puzzles, ordered easiest tier first.</summary>
    public static IReadOnlyList<ICard> All { get; } = Build();

    private static IReadOnlyList<ICard> Build() =>
    [
        // ── WARM-UP — many routes in; good for building confidence ───────────
        P(WarmUpCategory, "2 4 6 8", "2 4 6 8",
          "((4 × 8) - 2) - 6 = 24", Difficulty.Easy),            // 53 solutions
        P(WarmUpCategory, "2 3 4 6", "2 3 4 6",
          "(2 + 4) + (3 × 6) = 24", Difficulty.Easy),            // 28 solutions
        P(WarmUpCategory, "1 2 4 6", "1 2 4 6",
          "(2 + 6) × (4 - 1) = 24", Difficulty.Easy),            // 11 solutions
        P(WarmUpCategory, "3 4 6 8", "3 4 6 8",
          "(3 × 4) × (8 - 6) = 24", Difficulty.Easy),            // 13 solutions
        P(WarmUpCategory, "4 4 6 8", "4 4 6 8",
          "(4 + 8) × (6 - 4) = 24", Difficulty.Easy),            // 7 solutions
        P(WarmUpCategory, "3 3 4 8", "3 3 4 8",
          "(3 + 3) × (8 - 4) = 24", Difficulty.Easy),            // 12 solutions
        P(WarmUpCategory, "2 2 5 6", "2 2 5 6",
          "(2 + 6) × (5 - 2) = 24", Difficulty.Easy),            // 4 solutions
        P(WarmUpCategory, "1 5 6 8", "1 5 6 8",
          "6 × ((1 + 8) - 5) = 24", Difficulty.Easy),            // 5 solutions
        P(WarmUpCategory, "2 8 10 10", "2 8 10 10",
          "(10 + 10) + (8 ÷ 2) = 24", Difficulty.Easy),          // 9 solutions

        // ── STEADY — a real search, but nothing exotic ───────────────────────
        P(SteadyCategory, "1 3 4 5", "1 3 4 5",
          "(1 + 3) + (4 × 5) = 24", Difficulty.Medium),          // 12 solutions
        P(SteadyCategory, "2 3 5 7", "2 3 5 7",
          "(2 + 7) + (3 × 5) = 24", Difficulty.Medium),          // 12 solutions
        P(SteadyCategory, "5 6 7 8", "5 6 7 8",
          "(5 + 7) × (8 - 6) = 24", Difficulty.Medium),          // 12 solutions
        P(SteadyCategory, "4 5 6 7", "4 5 6 7",
          "(5 + 7) × (6 - 4) = 24", Difficulty.Medium),          // 7 solutions
        P(SteadyCategory, "1 4 8 9", "1 4 8 9",
          "(1 + (4 × 8)) - 9 = 24", Difficulty.Medium),          // 12 solutions
        P(SteadyCategory, "2 3 8 9", "2 3 8 9",
          "(8 × (9 - 3)) ÷ 2 = 24", Difficulty.Medium),          // 7 solutions
        P(SteadyCategory, "1 2 3 12", "1 2 3 12",
          "(1 + 3) × (12 ÷ 2) = 24", Difficulty.Medium),         // 12 solutions
        P(SteadyCategory, "3 5 7 8", "3 5 7 8",
          "((5 × 7) - 3) - 8 = 24", Difficulty.Medium),          // 11 solutions
        P(SteadyCategory, "2 5 8 11", "2 5 8 11",
          "(11 - 5) × (8 ÷ 2) = 24", Difficulty.Medium),         // 7 solutions
        P(SteadyCategory, "4 6 7 9", "4 6 7 9",
          "(6 × (7 + 9)) ÷ 4 = 24", Difficulty.Medium),          // 6 solutions

        // ── TRICKY — one or two routes, and they hide well ───────────────────
        P(TrickyCategory, "1 2 7 12", "1 2 7 12",
          "12 + (2 × (7 - 1)) = 24", Difficulty.Hard),           // 2 solutions
        P(TrickyCategory, "1 6 7 9", "1 6 7 9",
          "(1 + 7) × (9 - 6) = 24", Difficulty.Hard),            // 2 solutions
        P(TrickyCategory, "1 5 9 13", "1 5 9 13",
          "(1 + 5) × (13 - 9) = 24", Difficulty.Hard),           // 2 solutions
        P(TrickyCategory, "1 7 9 11", "1 7 9 11",
          "(1 + 11) × (9 - 7) = 24", Difficulty.Hard),           // 2 solutions
        P(TrickyCategory, "5 7 8 10", "5 7 8 10",
          "(10 - 8) × (5 + 7) = 24", Difficulty.Hard),           // 2 solutions
        P(TrickyCategory, "3 4 4 10", "3 4 4 10",
          "(4 × (10 - 3)) - 4 = 24", Difficulty.Hard),           // 1 solution
        P(TrickyCategory, "3 8 8 10", "3 8 8 10",
          "((8 × 10) - 8) ÷ 3 = 24", Difficulty.Hard),           // 1 solution
        P(TrickyCategory, "All Sixes", "6 6 6 6",
          "((6 × 6) - 6) - 6 = 24", Difficulty.Hard),            // 4 solutions

        // ── LEGENDARY — every route needs a fraction on the way ──────────────
        // These are the ones that stop maths teachers. Whole-number thinking
        // cannot reach 24 from any of them; you have to be willing to hold a
        // third or a quarter mid-calculation.
        P(LegendaryCategory, "The Famous One", "1 3 4 6",
          "6 ÷ (1 - (3 ÷ 4)) = 24", Difficulty.Extreme),         // 1 solution, fractional
        P(LegendaryCategory, "Almost a Whole", "1 4 5 6",
          "4 ÷ (1 - (5 ÷ 6)) = 24", Difficulty.Extreme),         // 2 solutions, fractional
        P(LegendaryCategory, "The Twelve Trap", "2 3 5 12",
          "12 ÷ (3 - (5 ÷ 2)) = 24", Difficulty.Extreme),        // 1 solution, fractional
        P(LegendaryCategory, "Twin Pairs", "3 3 8 8",
          "8 ÷ (3 - (8 ÷ 3)) = 24", Difficulty.Extreme),         // 1 solution, fractional
        P(LegendaryCategory, "2 4 10 10", "2 4 10 10",
          "10 × (2 + (4 ÷ 10)) = 24", Difficulty.Extreme),       // 1 solution, fractional
        P(LegendaryCategory, "5 5 7 11", "5 5 7 11",
          "5 × (7 - (11 ÷ 5)) = 24", Difficulty.Extreme),        // 1 solution, fractional
        P(LegendaryCategory, "Two Elevens", "2 2 11 11",
          "11 × (2 + (2 ÷ 11)) = 24", Difficulty.Extreme),       // 1 solution, fractional
    ];

    /// <summary>
    /// Builds one puzzle card. The <c>Answer:</c> line is what
    /// <c>CardFaces.Split</c> looks for, so the numbers show face-up and the
    /// worked solution lands on the flip side rather than spoiling the puzzle.
    /// </summary>
    private static ICard P(string category, string title, string numbers, string solution, Difficulty d) =>
        StandardCard.Create(
            title,
            "<b>🔢 MATH 24 — " + category.ToUpperInvariant() + "</b>\n\n" +
            "<b>" + numbers + "</b>\n\n" +
            "<i>Use all four numbers exactly once. Combine them with + − × ÷ and " +
            "brackets, in any order, to make exactly 24.</i>\n\n" +
            "Answer: " + solution +
            "\n(Other routes may exist — any correct one scores.)",
            d, category);
}
