using System.Text.RegularExpressions;
using TableTop.Core.Abstractions.Game;
using TableTop.Games.School;

namespace TableTop.Tests;

/// <summary>
/// Zero test references before this. The interesting half is
/// <see cref="EveryPuzzle_IsActuallySolvable"/>: the deck was generated by an
/// external solver, and this re-solves every card independently inside the
/// suite so the claim survives anyone hand-editing a quad later.
/// </summary>
public sealed class Math24ModeTests
{
    // ── Registration ──────────────────────────────────────────────────────────

    [Fact]
    public void RegisteredInArchetypeTree_AtTheExpectedId()
    {
        var node = ArchetypeRegistry.Default().FindById("classroom.math24");
        node.Should().NotBeNull();
        node.Modes.Should().Contain(m => m.Name == "Math 24");
    }

    [Fact]
    public void AgeRating_IsAllAges()
    {
        // The whole Classroom section is AllAges; a maths drill has no reason
        // to be the exception.
        ArchetypeRegistry.Default().FindById("classroom.math24")!
            .AgeRating.Should().Be(AgeRating.AllAges);
    }

    // ── Deck shape ────────────────────────────────────────────────────────────

    [Fact]
    public void Deck_HasCardsAcrossAllFourTiers()
    {
        var deck = new Math24Mode().GetCards([]);
        deck.Should().NotBeEmpty();
        deck.Select(c => c.Category).Distinct().Should().BeEquivalentTo(
            ["Warm-Up", "Steady", "Tricky", "Legendary"]);
    }

    [Fact]
    public void Deck_HasNoDuplicateBodiesOrIds()
    {
        var deck = new Math24Mode().GetCards([]);
        deck.Select(c => c.Description).Distinct().Should().HaveCount(deck.Count);
        deck.Select(c => c.Id).Distinct().Should().HaveCount(deck.Count);
    }

    [Fact]
    public void Deck_HasNoDuplicatePuzzles()
    {
        // Two cards showing the same four numbers would deal the same puzzle
        // twice in one sitting, which reads as a bug to a table.
        var quads = new Math24Mode().GetCards([]).Select(NumbersOf).ToList();
        quads.Select(q => string.Join(",", q.Order())).Distinct()
             .Should().HaveCount(quads.Count);
    }

    [Fact]
    public void Deck_IdsAreStable_AcrossRepeatedCalls()
    {
        var mode = new Math24Mode();
        mode.GetCards([]).Select(c => c.Id)
            .Should().Equal(mode.GetCards([]).Select(c => c.Id));
    }

    [Fact]
    public void Manifest_ReportsNonZeroTotalCards()
    {
        // Backlog item 10's bug class: a mode reporting zero is silently
        // excluded from every SurpriseMe(maxCards:) query.
        new Math24Mode().GetManifest().TotalCards.Should().BeGreaterThan(0);
    }

    // ── The puzzles themselves ────────────────────────────────────────────────

    [Fact]
    public void EveryCard_ShowsExactlyFourNumbers()
    {
        foreach (var card in new Math24Mode().GetCards([]))
            NumbersOf(card).Should().HaveCount(4,
                $"'{card.Title}' must present exactly four numbers to combine");
    }

    [Fact]
    public void EveryCard_HasAnAnswerLine_SoTheSolutionLandsOnTheFlipSide()
    {
        // CardFaces.Split keys on a line starting "Answer:" — without it the
        // solution renders face-up and spoils the puzzle before anyone reads it.
        foreach (var card in new Math24Mode().GetCards([]))
            card.Description.Should().Contain("Answer:",
                $"'{card.Title}' would otherwise print its solution on the front");
    }

    /// <summary>
    /// Re-solves every puzzle from scratch. This is the load-bearing test:
    /// an unsolvable card in a maths game sends a child chasing something
    /// impossible, and that failure is invisible to every other check here.
    /// </summary>
    [Fact]
    public void EveryPuzzle_IsActuallySolvable()
    {
        var unsolvable = new Math24Mode().GetCards([])
            .Where(c => !Solvable(NumbersOf(c)))
            .Select(c => $"{c.Title} ({string.Join(" ", NumbersOf(c))})")
            .ToList();

        unsolvable.Should().BeEmpty(
            "every Math 24 card must have at least one route to 24");
    }

    /// <summary>
    /// The printed solution must itself be correct — a card can be solvable
    /// while its worked answer has a typo, and the flip side is exactly what
    /// a table trusts when they give up.
    /// </summary>
    [Fact]
    public void EveryPrintedSolution_UsesTheCardsOwnNumbers()
    {
        foreach (var card in new Math24Mode().GetCards([]))
        {
            var shown = NumbersOf(card).Order().ToList();
            var used = Regex.Matches(AnswerOf(card), @"\d+")
                            .Select(m => int.Parse(m.Value))
                            .Where(n => n != 24)          // the '= 24' target
                            .Order().ToList();

            used.Should().Equal(shown,
                $"'{card.Title}' prints a solution using numbers other than its own");
        }
    }

    [Fact]
    public void LegendaryPuzzles_AllRequireAFractionalStep()
    {
        // This is what the tier means, and it is the reason 1 3 4 6 defeats
        // adults. If a Legendary card were reachable with whole numbers only,
        // it belongs in Tricky.
        foreach (var card in new Math24Mode().GetCards([]).Where(c => c.Category == "Legendary"))
            RequiresFraction(NumbersOf(card)).Should().BeTrue(
                $"'{card.Title}' is filed Legendary but has a whole-number route");
    }

    // ── Helpers: an independent 24-solver over exact rationals ────────────────
    //
    // Deliberately a second implementation rather than a call into anything the
    // deck was built with — a generator checked against itself proves nothing.
    // Rationals, not doubles: 6 ÷ (1 - 3÷4) is exactly 24 and would otherwise
    // fail an equality test by a rounding hair.

    private static List<int> NumbersOf(TableTop.Core.Abstractions.Cards.ICard card)
    {
        // The numbers line is the bolded one after the header.
        var line = TableTop.Hosting.CardText.StripHtml(card.Description)
            .Split('\n', StringSplitOptions.RemoveEmptyEntries)
            .Skip(1)
            .First(l => Regex.IsMatch(l.Trim(), @"^\d+(\s+\d+)*$"));

        return Regex.Matches(line, @"\d+").Select(m => int.Parse(m.Value)).ToList();
    }

    private static string AnswerOf(TableTop.Core.Abstractions.Cards.ICard card) =>
        TableTop.Hosting.CardText.StripHtml(card.Description)
            .Split('\n')
            .First(l => l.TrimStart().StartsWith("Answer:", StringComparison.Ordinal));

    private static bool Solvable(List<int> nums) =>
        Reachable(nums.Select(n => ((long)n, 1L)).ToList(), requireFraction: false, sawFraction: false)
            .Any();

    private static bool RequiresFraction(List<int> nums)
    {
        var paths = Reachable(nums.Select(n => ((long)n, 1L)).ToList(),
                              requireFraction: false, sawFraction: false).ToList();
        return paths.Count > 0 && paths.All(sawFraction => sawFraction);
    }

    /// <summary>
    /// Every way of combining <paramref name="items"/> down to one value that
    /// equals 24, yielding whether that route passed through a non-integer.
    /// Values are (numerator, denominator) pairs kept in lowest terms.
    /// </summary>
    private static IEnumerable<bool> Reachable(
        List<(long Num, long Den)> items, bool requireFraction, bool sawFraction)
    {
        if (items.Count == 1)
        {
            if (items[0].Num == 24 * items[0].Den) yield return sawFraction;
            yield break;
        }

        for (var i = 0; i < items.Count; i++)
            for (var j = i + 1; j < items.Count; j++)
            {
                var (an, ad) = items[i];
                var (bn, bd) = items[j];
                var rest = items.Where((_, k) => k != i && k != j).ToList();

                foreach (var (n, d) in Combine(an, ad, bn, bd))
                {
                    var (rn, rd) = Reduce(n, d);
                    foreach (var r in Reachable([.. rest, (rn, rd)],
                                                requireFraction,
                                                sawFraction || rd != 1))
                        yield return r;
                }
            }
    }

    private static IEnumerable<(long, long)> Combine(long an, long ad, long bn, long bd)
    {
        yield return (an * bd + bn * ad, ad * bd);   // a + b
        yield return (an * bd - bn * ad, ad * bd);   // a - b
        yield return (bn * ad - an * bd, ad * bd);   // b - a
        yield return (an * bn, ad * bd);             // a × b
        if (bn != 0) yield return (an * bd, ad * bn); // a ÷ b
        if (an != 0) yield return (bn * ad, bd * an); // b ÷ a
    }

    private static (long, long) Reduce(long n, long d)
    {
        if (d < 0) { n = -n; d = -d; }
        var g = Gcd(Math.Abs(n), d);
        return g == 0 ? (n, d) : (n / g, d / g);
    }

    private static long Gcd(long a, long b) => b == 0 ? a : Gcd(b, a % b);
}
