using System.Text;

namespace TableTop.DeckDesigner.Core;

/// <summary>
/// Renders a <see cref="DeckDraft"/> as the C# source of a static card-bank
/// class — the same shape every hand-written <c>*CardBank</c> in
/// <c>TableTop.Games</c> has taken since the migration onto
/// <see cref="TableTop.Core.Domain.Cards.CardDeckBuilder"/> (see
/// <c>ChronologyChallengeCardBank</c> for a representative example): a
/// <c>Deck</c> constant, a public <c>All</c> property, and a <c>Build()</c>
/// that chains <c>.Category(...)</c> / <c>.Card(...)</c> /
/// <c>.ThisOrThatCard(...)</c> calls.
///
/// <para>
/// This only ever emits a card bank, never a full <c>IGameModeDefinition</c> —
/// wiring one up (scoring strategy, category colours, complete/skip labels)
/// is a per-mode decision the tool has no basis to make, so that stays a
/// manual step: paste the generated class into a new file under
/// <c>src/TableTop.Games</c> and write the mode class around it, same as
/// every other mode.
/// </para>
/// </summary>
public static class CardBankCodeGenerator
{
    /// <summary>
    /// Generates the source text for a card-bank class named
    /// <paramref name="className"/> in <paramref name="namespaceName"/>,
    /// built from <paramref name="deck"/>. Does not validate — call
    /// <see cref="DeckCompiler.Compile(DeckDraft)"/> first, since generating
    /// code for a deck that fails to compile produces source that will not
    /// build either.
    /// </summary>
    public static string Generate(DeckDraft deck, string namespaceName, string className)
    {
        ArgumentNullException.ThrowIfNull(deck);
        ArgumentException.ThrowIfNullOrWhiteSpace(namespaceName);
        ArgumentException.ThrowIfNullOrWhiteSpace(className);

        var sb = new StringBuilder();

        sb.AppendLine("using TableTop.Core.Abstractions.Cards;");
        sb.AppendLine("using TableTop.Core.Domain.Cards;");
        sb.AppendLine();
        sb.Append("namespace ").Append(namespaceName).AppendLine(";");
        sb.AppendLine();
        sb.Append("/// <summary>Card bank for \"").Append(deck.Name)
          .AppendLine("\" — generated by the Deck Designer tool.</summary>");
        sb.Append("public static class ").AppendLine(className);
        sb.AppendLine("{");
        sb.Append("    private const string Deck = ").Append(Quote(deck.Name)).AppendLine(";");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Every card in this bank.</summary>");
        sb.AppendLine("    public static IReadOnlyList<ICard> All { get; } = Build();");
        sb.AppendLine();
        sb.AppendLine("    private static IReadOnlyList<ICard> Build() =>");
        sb.Append("        CardDeckBuilder.For(Deck)");

        AppendCards(sb, deck);

        sb.AppendLine();
        sb.AppendLine("            .Build();");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private static void AppendCards(StringBuilder sb, DeckDraft deck)
    {
        string? currentCategory = null;

        foreach (var card in deck.Cards)
        {
            if (currentCategory != card.Category)
            {
                sb.AppendLine();
                sb.Append("            .Category(").Append(Quote(card.Category)).Append(')');
                currentCategory = card.Category;
            }

            sb.AppendLine();
            if (card.IsThisOrThat)
                AppendThisOrThatCard(sb, card);
            else
                AppendStandardCard(sb, card);
        }
    }

    private static void AppendStandardCard(StringBuilder sb, CardDraft card)
    {
        sb.Append("            .Card(")
          .Append(Quote(card.Title)).Append(", ")
          .Append(Quote(card.Description)).Append(", ")
          .Append("Difficulty.").Append(card.Difficulty);

        if (card.Tags.Count > 0)
        {
            sb.Append(", tags: new[] { ")
              .Append(string.Join(", ", card.Tags.Select(Quote)))
              .Append(" }");
        }

        sb.Append(')');
    }

    private static void AppendThisOrThatCard(StringBuilder sb, CardDraft card)
    {
        sb.Append("            .ThisOrThatCard(")
          .Append(Quote(card.Title)).Append(", ")
          .Append(Quote(card.Description)).Append(", ")
          .Append("new ThisOrThatOption(").Append(Quote(card.OptionALabel))
          .Append(FormatDetail(card.OptionADetail)).Append("), ")
          .Append("new ThisOrThatOption(").Append(Quote(card.OptionBLabel))
          .Append(FormatDetail(card.OptionBDetail)).Append("), ")
          .Append("Difficulty.").Append(card.Difficulty)
          .Append(')');
    }

    private static string FormatDetail(string? detail) =>
        string.IsNullOrWhiteSpace(detail) ? "" : $", Detail: {Quote(detail)}";

    /// <summary>
    /// A C# regular string literal for <paramref name="value"/> — escaped
    /// rather than verbatim (<c>@"..."</c>) so it stays correct regardless of
    /// content, including a trailing quote or backslash.
    /// </summary>
    private static string Quote(string value)
    {
        var escaped = value
            .Replace("\\", "\\\\")
            .Replace("\"", "\\\"")
            .Replace("\r\n", "\\n")
            .Replace("\n", "\\n")
            .Replace("\t", "\\t");
        return $"\"{escaped}\"";
    }
}
